// Inspect generated bytes before they are stored or attached to an article.
// An unavailable, incomplete, or ambiguous review must never approve an image.
const VALIDATION_MODEL = process.env.AI_IMAGE_VALIDATION_MODEL || process.env.AI_TEXT_MODEL || 'gpt-5.6-terra';

const REVIEW_INSTRUCTIONS = `You are the final visual quality reviewer for an editorial travel photograph.
Use a practical editorial standard. Accept a strong photorealistic image when it clearly illustrates
the main story subject and has no clearly visible, material defect. Reject only a defect you can see
with high confidence: a clearly wrong subject or materially important location, an obvious AI artifact,
impossible anatomy or orientation, a materially false depiction, or an otherwise visibly unusable image.
Do not turn supporting article context into a shot list. Do not require every article detail, every named
entity, a particular camera viewpoint, branded signage, destination-management cues, or an exact
recreation of a described scene. Do not reject a relevant image merely because it uses a different but
credible composition. For animals, accept a credible photorealistic portrayal of the correct animal;
reject only clearly wrong species or obvious impossible anatomy, not debatable expert-level morphology,
precise horn proportions, lip shape, pose, or subspecies markers.

Inspect the actual image closely, including small background figures. Reject malformed anatomy,
reversed or unnaturally rotated heads, impossible body positions, incorrect limb number or placement,
malformed faces or hands, duplicated, merged, floating or partially generated people, and distorted
background people. Reject impossible interactions with objects. For strollers, check that adults push
from behind using plausible handles, children sit and face naturally, and wheels, seats and frame
have physically correct geometry. Check vehicles, buildings, perspective and lighting for obvious
AI artifacts. Reject cartoon, illustration or synthetic-looking imagery when a real photograph was
requested. Reject major inaccuracies in recognizable locations, especially landmarks belonging to
another destination. Reject clear visible defects or material inaccuracies. Do not reject solely
because a minor background detail cannot be verified. Judge whether the image is credible and
suitable as an editorial hero image overall.

Separately judge semantic relevance. The visible image must credibly represent the main story subject.
The named location is mandatory only when it materially changes what the image claims or the image
contains recognizable location cues; never demand signage or a landmark merely to prove the location.
A correct subject in a plausible setting may be sufficient when exact destination identity is not
visually verifiable. A generic beach, mountain, sunset, forest or generic attraction scene is not
relevant merely because it is attractive or broadly travel related. Reject a category-level image when
the story names a specific park, city, event, attraction, ship, hotel or product and the visible scene has
no credible connection to the main subject. Reject geographically incompatible scenery. Set
relevance_acceptable independently; acceptable cannot be true when relevance is false.

Treat the title, location, entities and requested prompt as context, not separate visual requirements.
Do not infer an image is sound solely because its prompt asks for realism. List only rejection-worthy
issues. When accepting, return no issues and no correction. When rejecting, request only the minimum
change needed to fix the visible material defect; do not add new composition requirements.`;

const reviewSchema = {
  type: 'object',
  properties: {
    acceptable: { type: 'boolean' },
    relevance_acceptable: { type: 'boolean' },
    issues: { type: 'array', items: { type: 'string' } },
    correction: { type: 'string' },
  },
  required: ['acceptable', 'relevance_acceptable', 'issues', 'correction'],
  additionalProperties: false,
};

function imageMimeType(buffer) {
  if (buffer?.[0] === 0xff && buffer?.[1] === 0xd8) return 'image/jpeg';
  if (buffer?.subarray?.(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) return 'image/png';
  return 'image/png';
}

function assertCompletedReview(review) {
  if (typeof review?.acceptable !== 'boolean' || !Array.isArray(review.issues)
    || !review.issues.every((issue) => typeof issue === 'string') || typeof review.correction !== 'string') {
    throw new Error('Image review returned an invalid decision.');
  }
  return review;
}

async function validateGeneratedImage(imageBuffer, {
  title,
  subject = '',
  location = '',
  entities = [],
  category = '',
  imagePrompt,
}) {
  if (!Buffer.isBuffer(imageBuffer) || !imageBuffer.length || !process.env.OPENAI_API_KEY) {
    throw new Error('Image review requires generated bytes and an OpenAI API key.');
  }

  const response = await fetch('https://api.openai.com/v1/responses', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
    },
    signal: AbortSignal.timeout(120000),
    body: JSON.stringify({
      model: VALIDATION_MODEL,
      instructions: REVIEW_INSTRUCTIONS,
      input: [{
        role: 'user',
        content: [
          { type: 'input_text', text: `Article title: ${String(title).slice(0, 250)}\nMain visual subject: ${String(subject).slice(0, 180)}\nSupporting entities (context only): ${(Array.isArray(entities) ? entities : []).join(', ').slice(0, 600)}\nLocation: ${String(location || '').slice(0, 120)}\nCategory: ${String(category || '').slice(0, 40)}\nImage request: ${String(imagePrompt).slice(0, 2500)}\nIs this image both relevant to this exact story and acceptable as a realistic editorial hero photograph?` },
          { type: 'input_image', image_url: `data:${imageMimeType(imageBuffer)};base64,${imageBuffer.toString('base64')}`, detail: 'high' },
        ],
      }],
      max_output_tokens: 2000,
      reasoning: { effort: 'low' },
      text: { format: { type: 'json_schema', name: 'article_image_review', schema: reviewSchema, strict: true } },
    }),
  });

  if (!response.ok) throw new Error(`Image review API returned HTTP ${response.status}.`);
  const data = await response.json();
  if (data.status !== 'completed') {
    const status = ['incomplete', 'failed', 'cancelled', 'queued', 'in_progress'].includes(data.status)
      ? data.status : 'unknown';
    const reason = ['max_output_tokens', 'content_filter'].includes(data.incomplete_details?.reason)
      ? data.incomplete_details.reason : 'unknown';
    throw new Error(`Image review did not complete (status=${status}, incomplete_reason=${reason}).`);
  }
  const output = data.output_text || (data.output || []).flatMap((item) =>
    item.type === 'message' ? (item.content || []).filter((part) => part.type === 'output_text').map((part) => part.text) : []
  ).join('');
  let review;
  try { review = JSON.parse(output); } catch { throw new Error('Image review returned invalid JSON.'); }
  if (typeof review.acceptable !== 'boolean' || typeof review.relevance_acceptable !== 'boolean'
    || !Array.isArray(review.issues)
    || !review.issues.every((issue) => typeof issue === 'string') || typeof review.correction !== 'string') {
    throw new Error('Image review returned an invalid decision.');
  }
  return {
    acceptable: review.acceptable === true && review.relevance_acceptable === true
      && review.issues.length === 0 && review.correction.trim() === '',
    relevanceAcceptable: review.relevance_acceptable,
    issues: review.issues,
    correction: review.correction,
  };
}

module.exports = { REVIEW_INSTRUCTIONS, assertCompletedReview, imageMimeType, validateGeneratedImage };
